server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yvon?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  # jpa配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 100MB


# mybatis-plus配置
mybatis-plus:
  mapper-locations:classpath: mapper/*Mapper.xml
  type-aliases-package: com.yvon.fileupdate.entity
  # 开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
    # 显示sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


oss:
  type: minio
  minio:
    access-key: minio
    secret-key: 123456
    endpoint: http://localhost:9000
  aliyun:
    access-key-id: 111
    access-key-secret: 222
    endpoint: oss-cn-hangzhou.aliyuncs.com








